import { GenderAbbreviation, maritalStatusAbbreviation, StateAbbreviation, EducationLevelAbbreviation, languageLevelAbbreviation, statusAbbreviation } from "../utils/constants";

export interface ResumeType {
    id: number;
    name: string;
    user: number;
    cpf: string;
    gender: GenderAbbreviation;
    birthDate: string;
    birthPlace: string;
    maritalStatus: maritalStatusAbbreviation;
    availability: string;
    spouseName?: string;
    spouseProfession?: string;
    hasChildren?: boolean;
    childrenAges?: string;
    isSmoker?: boolean;
    hasCar?: boolean;
    hasDisability?: boolean;
    disabilityCid?: string;
    address: string;
    neighborhood: string;
    city: string;
    state: StateAbbreviation;
    cep: string;
    phone: string;
    contactPhone?: string;
    email: string;
    linkedin?: string;
    educationLevel: EducationLevelAbbreviation;
    educationDetails: string;
    englishLevel: languageLevelAbbreviation;
    spanishLevel: languageLevelAbbreviation;
    otherLanguages?: string;
    computerSkills?: string;
    additionalCourses?: string;
    desiredPositions: number[];
    expectedSalary?: number;
    availableFullTime?: boolean;
    availableMorningAfternoon?: boolean;
    availableAfternoonNight?: boolean;
    availableNightShift?: boolean;
    available1236?: boolean;
    availableAsSubstitute?: boolean;
    status: statusAbbreviation;
}